### ISSUE TITLE
write hook into apples shortcut app

### ISSUE THREAD

**Issue by fdrechsler** [burned42/npradio#9]
Hey there, well, recently i bought this extremely pricy smart speaker from Apple and when i tred to explain the voice assistant that i would like to hear my favorite radio station i learned that it cant play Radio.....

People suggested me an App (https://www.radio-shorties.app/) but i really dont want to pay monthly for playing Internet Radio... actually they arent even streaming any data but just sending the play command to the HomePod. 

Do you see any chances providing an API and some Help to use your Project for building an Open Source Alternative?

**Comment by burned42** [comment]
Hey @fdrechsler, I don't own any Apple products so I can't really tell if this project will be of any use for what you want to do :) But you can check out https://hub.docker.com/r/burned42/npradio (I didn't link that anywhere here yet, did I? :D) and just spin up a container and look at the API and if that may be useful for an app for Apple's smart speaker ;)

Since I am just using this for myself I also didn't create an API spec yet, but I think you can also just take a look at the controller to see what's possible :D https://github.com/burned42/npradio/blob/master/src/Controller/ApiController.php

**Comment by fdrechsler** [comment]
Seems like everything I need for teaching Siri to play Radios 👍 
Thank you
